---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
#  - name: ubuntu-13.04-teamcity
  - name: centos-6.5
    driver:
      network:
        forwarded_port: {
          guest: 8111,
          host: 8111
        }
      customize:
        memory: 512

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer
      file_cache_path: /var/chef/cache/

suites:
  - name: default
    run_list:
      - recipe[teamcity::default]
    attributes: {
      java: {
        jdk_version: '7'
      },
      postgresql: {
        enable_pgdg_yum: true,
        version: '9.2',
        contrib: {
          packages: []
        },
        password: {
          postgres: 'pass123',
          teamcity: 'pass456'
        }
      }
    }
